// <auto-generated />
namespace ASP.NetLab6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StudentCoursesRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentCoursesRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201240555_StudentCoursesRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
